name: easy_init_cli
description: A CLI tool to create flutter project and initialize project with boilerplate code
version: 1.0.9
repository: https://github.com/Vineeth-Kolichal/easy_init_cli

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dcli: ^3.3.6
  process_run: ^0.14.2
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
executables:
  easy: easy_init_cli

platforms:
  linux:
  macos:
  windows: